[tool.poetry]
name = "gn2pg_client"
packages = [
    { include = "gn2pg" },
]
version = "0.0.6-dev"
description = "Import tool from GeoNature to a PostgreSQL database through Export module API (client side)"
authors = ["lpofredc <frederic.cloitre@lpo.fr>"]
maintainers = ["lpofredc <frederic.cloitre@lpo.fr>"]
license = "AGPL-3.0-or-later"
readme = "README.rst"
homepage = "https://github.com/lpoaura/gn2gn_client/"
keywords = ["GeoNature", "Export", "SINP", "opendata", "biodiversity"]
classifiers= [
        "Development Status :: 1 - Planning",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: French",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: Implementation :: PyPy",
        "Topic :: Documentation",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Installation/Setup",
        "Topic :: System :: Software Distribution",
    ]

[tool.poetry.scripts]
gn2pg_cli = "gn2pg.main:run"


[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
SQLAlchemy = "^1.3.22"
psycopg2-binary = "^2.8.6"
coloredlogs = "^15.0"
schema = "^0.7.3"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
black = "^20.8b1"
flake8 = "^3.8.4"
Sphinx = "^3.4.0"
coverage = "^5.3.1"
pylint = "^2.6.0"
mypy = "^0.790"
tox = "^3.20.1"
isort = "^5.6.4"
sphinx-rtd-theme = "^0.5.0"
pre-commit = "^2.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
